#import "../movies/MovieFragment.gql"
query GetUserRecommendedMovies($userId: ID!) {
	user: User(userId: $userId) {
		userId
		recommendedMovies(first: 10) {
			...movie
			genre: in_genre(first: 1) {
				name
			}
		}
	}
}
